module.exports = Object.freeze({

    PENDING_PAYMENT: "PENDING_PAYMENT",

    CONFIRMED: "CONFIRMED",

    PACKING: "PACKING",

    ASSIGNED: "ASSIGNED",

    OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",

    DELIVERED: "DELIVERED",

    RETURNED: "RETURNED",

    CANCELLED: "CANCELLED"

});