module.exports = {

    // General

    INTERNAL_SERVER_ERROR:"INTERNAL_SERVER_ERROR",

    VALIDATION_ERROR:"VALIDATION_ERROR",

    UNKNOWN_FIELD:"UNKNOWN_FIELD",

    METHOD_NOT_ALLOWED:"METHOD_NOT_ALLOWED",

    ROUTE_NOT_FOUND:"ROUTE_NOT_FOUND",

    // Authentication

    INVALID_CREDENTIALS:"INVALID_CREDENTIALS",

    INVALID_ACCESS_TOKEN:"INVALID_ACCESS_TOKEN",

    INVALID_REFRESH_TOKEN:"INVALID_REFRESH_TOKEN",

    ACCESS_TOKEN_EXPIRED:"ACCESS_TOKEN_EXPIRED",

    REFRESH_TOKEN_EXPIRED:"REFRESH_TOKEN_EXPIRED",

    ACCOUNT_NOT_FOUND:"ACCOUNT_NOT_FOUND",

    ACCOUNT_NOT_VERIFIED:"ACCOUNT_NOT_VERIFIED",

    ACCOUNT_INACTIVE:"ACCOUNT_INACTIVE",

    // User

    EMAIL_ALREADY_EXISTS:"EMAIL_ALREADY_EXISTS",

    PHONE_ALREADY_EXISTS:"PHONE_ALREADY_EXISTS",

    PROFILE_NOT_FOUND:"PROFILE_NOT_FOUND",

    // Database

    DUPLICATE_ENTRY:"DUPLICATE_ENTRY",

    FOREIGN_KEY_ERROR:"FOREIGN_KEY_ERROR",

    DATABASE_ERROR:"DATABASE_ERROR"

};