module.exports = {

    REGISTER: "REGISTER",

    FORGOT_PASSWORD: "FORGOT_PASSWORD",

    RESET_PASSWORD: "RESET_PASSWORD",

    DELETE_ACCOUNT: "DELETE_ACCOUNT",

    RESTORE_ACCOUNT: "RESTORE_ACCOUNT",

    CHANGE_EMAIL: "CHANGE_EMAIL",

    CHANGE_PHONE: "CHANGE_PHONE"

};